### ISSUE TITLE
Support for architectures like arm (e.g. raspberry rp) on docker hub

### ISSUE THREAD

**Issue by ghdoergeloh** [pact-foundation/pact-broker-docker#30]
I wanted to try the pact-broker-docker image from https://hub.docker.com/r/pactfoundation/pact-broker. Therefore I started a simple docker-compose.yml
```
version: "3"

services:
  postgres:
    image: postgres
    restart: always
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres

  pact_broker:
    image: pactfoundation/pact-broker
#    build: ./pact-broker-docker
    restart: always
    links:
      - postgres
    ports:
      - 9292:9292
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: secret
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
```
This did not work, because I am running on a banana pi (arm not amd64).

I think it would be nice for developers at home to try pact on a SBC like banana, raspberry or other fruits with a arm or arm64 architecture.

I tried the compatibility myself by cloning the repo and building it instead of using the existing image. It took a while to install everything, but now it works - as far as I can see for now. So I think it would only be another architecture in the pipeline to deploy the docker image on hub.docker.com and then we could use the pact broker on a SBC for small projects and tests at home.
